name: 开始每日签到

on:
  workflow_dispatch:
  schedule:
    # UTC 4点00分(北京时间 12点00分)
    # 4/8 从 UTC 4点00分(北京时间 12点00分) 开始每隔 8 小时签到一次，防止网络问题导致的签到不上
    - cron: 0 4/10 * * * 
  # 标星时触发工作流程
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout_action
      - uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install requests,datetime
          
      - name: Run checkin
        env: 
          TOKEN: "${{ secrets.TOKEN }}"
        run: |
          python3 ikuuuVPN_checkin.py
      - uses: gautamkrishnar/keepalive-workflow@master  
